rootProject.name = "ComposeDrawer"
include(":app")
include(":drawer-base")
include(":drawer-modules")
include(":drawer-ui-modules")
include(":drawer-retrofit")
include(":drawer-okhttplogger")
include(":drawer-leak")
include(":drawer-timber")
include(":drawer-location")
